#!/bin/bash

echo "🎨 Slack Warlock Render Deployment Guide"
echo "========================================"

echo ""
echo "📋 STEP 1: Create GitHub Repository"
echo "1. Go to https://github.com"
echo "2. Click '+' → 'New repository'"
echo "3. Name: slack-warlock"
echo "4. Create repository (don't initialize with README)"

echo ""
echo "📤 STEP 2: Push Your Code"
echo "Run these commands (replace YOUR_USERNAME):"
echo "git remote add origin https://github.com/YOUR_USERNAME/slack-warlock.git"
echo "git push -u origin main"

echo ""
echo "🚀 STEP 3: Deploy to Render"
echo "1. Go to https://render.com"
echo "2. Sign up/Login"
echo "3. Click 'New +' → 'Web Service'"
echo "4. Connect GitHub and select your repository"
echo "5. Configure:"
echo "   - Name: slack-warlock-bot"
echo "   - Environment: Node"
echo "   - Build Command: npm install"
echo "   - Start Command: npm start"

echo ""
echo "🔧 STEP 4: Add Environment Variables"
echo "In Render dashboard, go to Environment and add:"
echo ""
echo "SLACK_BOT_TOKEN=xoxb-your-token-here"
echo "SLACK_SIGNING_SECRET=your-signing-secret-here"
echo "SLACK_APP_TOKEN=xapp-your-app-token-here"
echo "OPENAI_API_KEY=sk-your-openai-key-here"
echo "GOOGLE_SHEETS_SPREADSHEET_ID=your-spreadsheet-id-here"
echo "GOOGLE_SERVICE_ACCOUNT_EMAIL=your-service-account@project.iam.gserviceaccount.com"
echo "GOOGLE_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----"
echo "YOUR_PRIVATE_KEY_HERE"
echo "-----END PRIVATE KEY-----"

echo ""
echo "✅ STEP 5: Deploy!"
echo "Click 'Create Web Service' and your bot will be live!"

echo ""
echo "📊 Benefits of Render:"
echo "✅ 750 hours/month free tier"
echo "✅ Automatic HTTPS"
echo "✅ GitHub integration"
echo "✅ Auto-deploys on git push"
echo "⚠️  Sleeps after 15 minutes (wakes on requests)"

echo ""
echo "🎉 Your Slack bot will be running 24/7 on Render!" 